query getIssueAndComments($name: String!, $owner: String!, $after: String) {
  repository(name: $name, owner: $owner) {
    issues(first: 100, after: $after, orderBy: { field: CREATED_AT, direction: DESC }) {
      totalCount
      edges {
        cursor
        node {
          id
          body
          closedAt
          createdAt
          state
          comments(first: 100) {
            nodes {
              id
              body
              createdAt
              author {
                login
              }
            }
          }
        }
      }
    }
  }
}
