query getCommitHistory($name: String!, $owner: String!, $after: String) {
  repository(name: $name, owner: $owner) {
    defaultBranchRef {
      id
      target {
        ... on Commit {
          history(after: $after) {
            edges {
              cursor
              node {
                id
                committedDate
                additions
                deletions
              }
            }
          }
        }
      }
    }
  }
}
