name: server CI
on:
  push:
    branches: [main]
    paths: [server/**]
  pull_request:
    branches: [main]
    paths: [server/**]

jobs:
  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.4
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn prisma generate
      - run: yarn tsc --noEmit
      - run: yarn test
      - run: yarn lint:check
